In [3]:
#first question

import numpy as np

x = np.array([[1,4],[6,9]])
x = x.tolist()
print(x)

[[1, 4], [6, 9]]


In [2]:
#second question

import numpy as np

array = np.array([[2,5],
                  [8,6]])

trace = np.trace(array)
print(trace)

8


In [9]:
#third question

import numpy as np

array = np.array([[16,1],[3,5]])

x=2

print(array[array>x])


[16  3  5]


In [11]:
#fourth question

import numpy as np
a = np.array([[1,5],[9,6]])
b = np.array([[3,9],[4,2]])

c = a+b
print(c)

[[ 4 14]
 [13  8]]


In [16]:
#fifth question

import numpy as np
a = np.array([[2,5],[6,7]])
b = a-np.mean(a)
b


array([[-3.,  0.],
       [ 1.,  2.]])